# Generated by Django 4.2.5 on 2023-09-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
